models:
  active: GaussianCopula

  TVAE:  
    data_path: ./Synthetic_Dataset_run_06_12_2021_163219.xlsx
    primary_key: ID
    epochs: 1
    batch_size: 500 
    num_rows: 200
    Anonymization:
      active: False
      name_of_the_fields: []
      category_of_the_fields: []
   
      

  CopulaGAN:  
    data_path: ./Synthetic_Dataset_run_06_12_2021_163219.xlsx
    primary_key: ID
    epochs: 1
    batch_size: 500 
    num_rows: 200
    Anonymization:
      active: False
      name_of_the_fields: []
      category_of_the_fields: []
    field_distributions: {}  

  GaussianCopula:  
    data_path: ./Synthetic_Dataset_run_06_12_2021_163219.xlsx
    primary_key: ID
    num_rows: 200
    Anonymization:
      active: False
      name_of_the_fields: []
      category_of_the_fields: []
    field_distributions: {}  
